source 'https://github.com/CocoaPods/Specs.git'

target 'SBCategories', :exclusive => true do
  pod "SBCategories", :path => "../"

  pod 'Specta'
  pod 'Expecta'
end

post_install do |installer|
    project = installer.project
    if (project)
        project.build_configurations.each do |config|
            s = config.build_settings['ONLY_ACTIVE_ARCH']
            s = 'NO' if s == 'YES';
            config.build_settings['ONLY_ACTIVE_ARCH'] = s
        end
    else
        puts "WARNING: Pods project not found!"
    end
end

#post_install do |installer|
#    target = installer.project.targets.find { |t| t.to_s == "Pods-SBCategories-Specta" }
#    if (target)
#        target.build_configurations.each do |config|
#            s = config.build_settings['FRAMEWORK_SEARCH_PATHS']
#            s = [ '$(inherited)' ] if s == nil;
#            s.push('$(PLATFORM_DIR)/Developer/Library/Frameworks')
#            config.build_settings['FRAMEWORK_SEARCH_PATHS'] = s
#        end
#    else
#        puts "WARNING: Pods-SBCategories-Specta target not found"
#    end
#end
